### PR TITLE
fix: do not crash when workers exceed commits

### LINKED ISSUE #98: Crashes when using --git-parallel
While running betterleaks it crashes for many projects with a similar error

```sh
Command '['betterleaks', 'git', '.project', '--report-format', 'json', '--report-path', PosixPath('/builds/<censored>'), '--config', 'gitleaks.toml', '--git-workers', '8']' returned non-zero exit status 2.


  ○
  ○
  ●
  ○  betterleaks 1.1.2

[90m11:54PM[0m [32mINF[0m [1mUnknown SCM platform. Use --platform to include links in findings.[0m [36mhost=[0mcode.siemens.com
[90m11:54PM[0m [32mINF[0m [1mparallel git scan[0m [36mchunk_size=[0m2 [36mcommits=[0m10 [36mworkers=[0m8
panic: runtime error: slice bounds out of range [12:10]
goroutine 1 [running]:
github.com/betterleaks/betterleaks/sources.(*ParallelGit).Fragments(0xf775b699500, {0x1371d20, 0x20026e0}, 0xf775c7f2040)
	/Users/zrice/code/betterleaks/betterleaks/sources/parallel_git.go:73 +0x399
github.com/betterleaks/betterleaks/detect.(*Detector).DetectSource(0xf775b7062c8, {0x1371d20, 0x20026e0}, {0x1365660, 0xf775b699500})
	/Users/zrice/code/betterleaks/betterleaks/detect/detect.go:331 +0x18b
github.com/betterleaks/betterleaks/cmd.runGit(0x1fd0300, {0xf775b635dd0, 0x1, 0x12aaec9?})
	/Users/zrice/code/betterleaks/betterleaks/cmd/git.go:112 +0x6bd
github.com/spf13/cobra.(*Command).execute(0x1fd0300, {0xf775b635d40, 0x9, 0x9})
	/Users/zrice/go/pkg/mod/github.com/spf13/cobra@v1.10.1/command.go:1019 +0xafb
github.com/spf13/cobra.(*Command).ExecuteC(0x1fcfa60)
	/Users/zrice/go/pkg/mod/github.com/spf13/cobra@v1.10.1/command.go:1148 +0x465
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/zrice/go/pkg/mod/github.com/spf13/cobra@v1.10.1/command.go:1071
github.com/betterleaks/betterleaks/cmd.Execute()
	/Users/zrice/code/betterleaks/betterleaks/cmd/root.go:297 +0x1e
main.main()
	/Users/zrice/code/betterleaks/betterleaks/main.go:18 +0x9
```

### PR DESCRIPTION
**Pull request by max-wittig**
Closes https://github.com/betterleaks/betterleaks/issues/98

### CODE REVIEW

**Comment by max-wittig** [comment]
@zricethezav I'm not too familiar with the codebase. I just basically threw this into Opus and did some sanity checks. What do you think about this?

File: sources/parallel_git.go [hunk 1]
```diff
@@ -69,6 +69,9 @@ func (s *ParallelGit) Fragments(ctx context.Context, yield FragmentsFunc) error
 	g, gctx := errgroup.WithContext(ctx)
 	for i := range workers {
 		start := i * chunkSize
+		if start >= count {
+			break
+		}
```
Comment (rgmz) [inline sources/parallel_git.go:74]: This is probably the easiest fix. We already clamp `workers` above for a similar reason.
```go
	count := len(commits)
	workers := s.workers()
	if count == 0 {
		return nil
	}
	if workers > count {
		workers = count
	}
```

Comment (max-wittig) [reply sources/parallel_git.go:74]: So you're okay with this approach?

**Comment by max-wittig** [comment]
@rgmz Back to you!

**Review by zricethezav — APPROVED** [review]
